"Vundle Stuff
set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
Plugin 'flazz/vim-colorschemes'
Plugin 'fatih/vim-go'

call vundle#end()
filetype plugin indent on


"Colors
colorscheme molokai
syntax on

"Spacing and Tabs
set tabstop=4
set softtabstop=4
set expandtab

"UI Config
set number
set showcmd
set cursorline
filetype indent on
set wildmenu
set lazyredraw
set showmatch

"Searching
set incsearch
set hlsearch
nnoremap <leader><space> :nohlsearch<CR>

"Movement

"Leader Shortcuts

"Launch Config